### ISSUE TITLE
Slateport Beach Trainer Issues

### ISSUE THREAD

**Issue by Ryan-Gole** [kelseyyoung/EmeraldIronmonMap#11]
Tuber Chandler, Tuber Ricky, and Sailor Edmond are all listed as spinners, but they don't spin.

Beyond those 3, the main issue is just that four of the sprites on the map are facing the wrong way. Tuber Lola and Tuber Haley both face right, and Sailor Edmond and Tuber Chandler both face left.

I'm not sure if you just don't have images for the sprites facing the other way, but Tuber Jani and Tuber Charlie you have elsewhere on the map facing other directions (though maybe you achieved this a different way).  

It's also possible that fixing this just isn't worth the effort if you have to manually make PNGs of these sprites facing other ways.

**Comment by Ryan-Gole** [comment]
Bird Keep Elijah is another the map shows facing down, but he faces right.

**Comment by kelseyyoung** [comment]
Fixed
