### ISSUE TITLE
Item missing in Meteor Falls

### ISSUE THREAD

**Issue by Ryan-Gole** [kelseyyoung/EmeraldIronmonMap#12]
![image](https://user-images.githubusercontent.com/20686777/194792603-37b12fb7-7c20-4e32-b49a-c51b29b0fe1d.png)
The route for meteor falls should probably also be updated to path to this item.

**Comment by Ryan-Gole** [comment]
Whether the path needs to be updated is a little debatable, since the current path goes to Steven which is only post E4, whereas this item can be obtained before the E4 since you're allowed to re-enter this cave.

**Comment by kelseyyoung** [comment]
I'll add the item, but I think I'll leave the route out for now
