### ISSUE TITLE
2 Missing items on route 128 (Ocean)

### ISSUE THREAD

**Issue by DevilHunterP12** [kelseyyoung/EmeraldIronmonMap#14]
Hi! 

There's 2 hidden items in the ocean of route 128 missing from the map. I marked the exact spots with X's. I'll add more zoomed in images below.

![Screenshot (41)](https://user-images.githubusercontent.com/122188842/211177744-3839fa7a-dbbb-49e7-89e5-fef1e029649b.jpg)

1 in the corner of a rock just north of the fisherman.

![hiddenItem2](https://user-images.githubusercontent.com/122188842/211177766-e01f45e3-2c91-4a98-b71f-ab8ca658fb9f.png)

1 on the right side of the walkable patch in front of a rock.

![hiddenItem1](https://user-images.githubusercontent.com/122188842/211177782-66cc5aca-fc68-48ac-a498-859e28c474b4.png)

Thanks for making such an amazing map, Kelsey! The Emerald Ironmon streamers send their massive thanks!

**Comment by kelseyyoung** [comment]
Fixed and deployed
