### ISSUE TITLE
[Route 127] Cooltrainer Athena is missing

### ISSUE THREAD

**Issue by palex00** [kelseyyoung/EmeraldIronmonMap#15]
![grafik](https://github.com/kelseyyoung/EmeraldIronmonMap/assets/32203971/22d656ef-a6e7-4a65-9671-f6a04f1a78a2)

Hi there. Great work. I found an issue, on Route 127 Cooltrainer Athena is uninteractable and her Trainer Data is missing.

**Comment by kelseyyoung** [comment]
This should now be fixed, thanks for reporting!
