### ISSUE TITLE
Two trainers missing in Team Magma Hideout

### ISSUE THREAD

**Issue by Ryan-Gole** [kelseyyoung/EmeraldIronmonMap#3]
![image](https://user-images.githubusercontent.com/20686777/193416835-731f753a-0592-481b-8e8f-90a58f2da1ba.png)
This is in the area between map links 3 and 4 (the bottom right image of the magma hideout).

**Comment by Ryan-Gole** [comment]
I'm realizing now you might've intentionally left this off because it's a double battle lol

Double battles are on the FRLG map though, so I think it would make sense to include this. Edit to clarify, I mean double battles where it's two trainers who are one entity are normally shown. I can't recall this type of forced double battle in FRLG.

Also, I just found another forced double battle for Cooltrainer Marley and Dragon Tamer Aaron and they are on the map.

**Comment by Ryan-Gole** [comment]
I think maybe it would make sense to add a new feature that's an icon for double battles where it's impossible to take them on individually. It would be similar to the walker and spinner ones, maybe just two stick figures standing next to each other.

Like this
https://www.kissclipart.com/two-people-holding-hands-icon-clipart-holding-hand-zoldn3/
![image](https://user-images.githubusercontent.com/20686777/193417904-9de5f9de-e94b-43af-aa56-7e223a40ce8b.png)

**Comment by kelseyyoung** [comment]
Yeah I've considered adding an icon for double battles in general ("traditional" ones where they're standing next to each other) but adding that for unavoidable doubles in Emerald would be a good idea too. As far as I know most of them in Emerald are optional via pathing but you're right there are a few

**Comment by kelseyyoung** [comment]
Closing this for adding the missing trainers, double battle icon tbd

**Comment by Ryan-Gole** [comment]
> Also, I just found another forced double battle for Cooltrainer Marley and Dragon Tamer Aaron and they are on the map.
![image](https://user-images.githubusercontent.com/20686777/194686252-087897b4-d348-4656-8829-ebbc41ef4fec.png)
Never mind about this part, you can actually take them on individually.
