### ISSUE TITLE
Items missing in Shoal Cave for Low Tide

### ISSUE THREAD

**Issue by Ryan-Gole** [kelseyyoung/EmeraldIronmonMap#4]
It seems you only had the high tide items for Shoal Cave before, but these ones should complete the cave according to bulbapedia items.

![image](https://user-images.githubusercontent.com/20686777/193418733-2b6e90cd-f0ee-4810-befc-a75aecc42773.png)
This is in the area between map portals 5 and 6.

![image](https://user-images.githubusercontent.com/20686777/193419001-6c7ec2e1-4b07-4dc2-a497-abc7e41051ca.png)
This is in the ice room, and it is a TM.

![image](https://user-images.githubusercontent.com/20686777/193419035-95ef5c62-d073-45ad-ba27-458c01d98930.png)
The other item in the ice room.

**Comment by kelseyyoung** [comment]
Fixed and deployed
