### ISSUE TITLE
Swimmer Susie is a spinner but isn't labeled as one

### ISSUE THREAD

**Issue by Ryan-Gole** [kelseyyoung/EmeraldIronmonMap#5]
This is a possible issue (walkers and spinners not being labeled) that I wasn't thinking of looking for before, but I noticed one a few trainers after I started looking for it.

I don't have a gif of it because I wasn't thinking of capturing it.

If I find any more and this issue is still open, I'll just add them as comments to this issue.

**Comment by kelseyyoung** [comment]
Yeah I'm sure there are more, I'll leave this issue open then. Appreciate it!

**Comment by Ryan-Gole** [comment]
Expert Conor is also a spinner.
![image](https://user-images.githubusercontent.com/20686777/193467886-134e31dd-932f-4fce-a985-33ca174c4408.png)

**Comment by Ryan-Gole** [comment]
Sailor Hudson is a spinner
![image](https://user-images.githubusercontent.com/20686777/193467980-9ae5170f-8a70-451f-ad56-0514d5eab759.png)

**Comment by kelseyyoung** [comment]
Spinners up to this comment have been added and deployed

**Comment by Ryan-Gole** [comment]
Black Belt Koji is also a spinner
![image](https://user-images.githubusercontent.com/20686777/193470539-e93dfa1d-3c4f-4d39-97f5-fad4bf0520b2.png)

**Comment by Ryan-Gole** [comment]
Swimmer Denise is a spinner
Swimmer Missy is a spinner
Swimmer Darrin is a spinner
Triathlete Camron is labeled as a spinner but isn't one.
Swimmer Tara is a spinner
Swimmer Alice is a spinner
Tuber Gwen is a spinner

**Comment by Ryan-Gole** [comment]
Pokemon Ranger Jackson is a spinner
![image](https://user-images.githubusercontent.com/20686777/194671120-6eb3c48d-0ab9-48f5-81f7-4f0df0ee82fe.png)
This aqua grunt in the weather institute is a spinner

**Comment by Ryan-Gole** [comment]
Parasol Lady Clarissa is a spinner
Bug Maniac Jeffery is a spinner
Ruin Maniac Chip is a spinner
Beauty Jessica is a spinner
Cooltrainer Marcel is a spinner

**Comment by Ryan-Gole** [comment]
Cooltrainer Braxton is a spinner

**Comment by Ryan-Gole** [comment]
Swimmer Spencer is a spinner
Triathlete Camden is a spinner
Bird Keeper Beck is a spinner

**Comment by kelseyyoung** [comment]
Spinners fixed up to this comment

**Comment by Ryan-Gole** [comment]
Lass Haley is labeled as a spinner but isn't one.

Additional Spinners:
Bug Catcher Lyle
Bug Catcher James
School Girl Karen
Youngster Joey
Youngster Johnson

**Comment by Ryan-Gole** [comment]
Pokemon Breeder Lydia is a spinner

**Comment by Ryan-Gole** [comment]
Hiker Trent is a spinner.
Picnicker Irene is a spinner.
Camper Travis is a spinner.
Cooltrainer Wilton is a spinner.
Youngster Dillon is a spinner.
Hiker Lucas is labeled as a spinner but isn't one.

**Comment by kelseyyoung** [comment]
Spinners fixed and deployed up to this comment

**Comment by kelseyyoung** [comment]
Closing since there haven't been any updates for a long time
