### ISSUE TITLE
2 Map Portals are swapped in Seafloor Cavern

### ISSUE THREAD

**Issue by Ryan-Gole** [kelseyyoung/EmeraldIronmonMap#7]
The map portal for 6 goes to 9 and the map portal for 9 goes to 6.
https://user-images.githubusercontent.com/20686777/193471705-fe3ce23d-6b5f-4987-b39c-94770f63888c.mp4

This also makes it so that the path shown for the route in Seafloor Cavern is a little bit off.
It's currently going to 9 here when it should be going to 6.
![image](https://user-images.githubusercontent.com/20686777/193471855-d2fbb2e8-002c-4756-a25a-43f4b4b5f8f3.png)

**Comment by kelseyyoung** [comment]
Wow that's really interesting, I was going off this map which shows the opposite >.< https://gamefaqs.gamespot.com/gba/921905-pokemon-emerald-version/map/13386-seafloor-cavern-map

**Comment by kelseyyoung** [comment]
Fixed
