### ISSUE TITLE
Pathing in Victory Road missing some obstacles

### ISSUE THREAD

**Issue by Ryan-Gole** [kelseyyoung/EmeraldIronmonMap#8]
![image](https://user-images.githubusercontent.com/20686777/193474795-61316137-0e27-4186-b9e1-6e973f4f799a.png)
This part is missing a second boulder and a rock smash rock.

https://user-images.githubusercontent.com/20686777/193474826-d4cc778b-df3d-4302-b36e-3847b53c354e.mp4

**Comment by kelseyyoung** [comment]
Fixed
