### ISSUE TITLE
Levels of Trainers in Meteor Falls

### ISSUE THREAD

**Issue by Ryan-Gole** [kelseyyoung/EmeraldIronmonMap#9]
Old Couple John and Jay have level 62 pokemon. (39 * 1.06 = 41.34; 41*1.5 = 61.5)
Dragon Tamer Nicolas has level 59 pokemon.
These are at least the levels in Emerald.

According to Bulbapedia, they're all one level higher in Ruby and Sapphire which should become 63 and 60

I'm not sure if they currently have zero for the levels because you didn't have a good way to show the different levels or if it was just that you didn't have the info.

**Comment by kelseyyoung** [comment]
yeah if it shows a ? for the levels it's because I didn't have the information

**Comment by kelseyyoung** [comment]
Fixed
